name: Update Screenshot

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: write

jobs:
  screenshot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci
      - run: npm run build
      - run: npm run screenshot
      - uses: EndBug/add-and-commit@v9
        with:
          add: screenshot.png
          message: "chore: update screenshot [skip ci]"
      - uses: actions/upload-artifact@v3
        with:
          name: screenshot
          path: screenshot.png

